require 'rbind/logger.rb'
require 'rbind/core/rbase.rb'
require 'rbind/core/rdata_type.rb'
require 'rbind/core/rconst.rb'
require 'rbind/core/renum.rb'
require 'rbind/core/rattribute.rb'
require 'rbind/core/rparameter.rb'
require 'rbind/core/roperation.rb'
require 'rbind/core/rgetter.rb'
require 'rbind/core/rsetter.rb'
require 'rbind/core/rnamespace.rb'
require 'rbind/core/rstruct.rb'
require 'rbind/core/rclass.rb'
require 'rbind/core/rreference.rb'
require 'rbind/core/rpointer.rb'
require 'rbind/core/rtype_qualifier.rb'

# TODO move somewhere else
require 'rbind/core/rvector.rb'
require 'rbind/core/rstring.rb'
